# -*- encoding: utf-8 -*-
from odoo import api, fields, models, _
import num2words


class PeLegend(models.Model):
    _name = "pe.legend"
    _description = "Sunat Legend"
    
    name = fields.Char("Name")
    code = fields.Selection("_get_code", "Code")
    move_id = fields.Many2one("account.move", "Move")
    is_auto = fields.Boolean("Autogenerated")
    
    _order = 'code ASC'
    
    @api.onchange('code')
    def _onchange_code(self):
        if self.code == '1000':
            amount = int(self.move_id.amount_total)
            cents = int((self.move_id.amount_total - amount)*100)
            self.name = num2words(amount, lang='es').upper() + " Y %s/100 %s" %(str(cents), (self.move_id.currency_id.currency_unit_label or self.move_id.currency_id.name).upper())
        elif self.code:
            self.name = self.env['pe.catalog.52'].get_by_code(self.code).name
    
    @api.model
    def _get_code(self):
        return self.env['pe.catalog.52'].get_selection()
    
